
### 端口配置
server:
  port: 80
  servlet:
    context-path: /mydemo

### 日志配置
logging:
  level:
   info: #root级别
   com.pxichen.mydemo: error #package级别
  file:
    name: logs/system.log

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    ### jpa配置 需要先建立好数据库，hibernate只会建表，不会建库
    #update: 会自动更新表结构
    #create: 会删除原来的表 新建所有的表
    #create-drop:会再每一次启动程序时创建表，关闭程序时自动删除

