
### 端口配置
server:
  port: 8080

### 日志配置
logging:
  level:
   info: #root级别
   com.pxichen.mydemo: warn #package级别
  file:
    name: logs/system.log
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    ### jpa配置 需要先建立好数据库，hibernate只会建表，不会建库
    #update: 会自动更新表结构
    #create: 会删除原来的表 新建所有的表
    #create-drop:会再每一次启动程序时创建表，关闭程序时自动删除

### 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydemo?serverTimeZone=UTC&userSSL=false
    data-username: root
    password: root

